### ISSUE TITLE
Error on calling initModal

### ISSUE THREAD

**Issue by rellfy** [Web3Auth/web3auth-pnp-examples#235]
When calling the initModal function on the Web3Auth instance, the following error is thrown:

```ts
TypeError: Class extends value undefined is not a constructor or null
    at node_modules/@toruslabs/torus-embed/node_modules/@metamask/obs-store/dist/asStream.js (asStream.ts:5:40)
    at __require2 (chunk-YS2TNBJ3.js?v=b4dcd89a:18:50)
    at node_modules/@toruslabs/torus-embed/node_modules/@metamask/obs-store/dist/index.js (index.ts:1:1)
    at __require2 (chunk-YS2TNBJ3.js?v=b4dcd89a:18:50)
    at browser.js:30:1
```

Calling connect afterwards (having the above `initModal` call within a try-catch) opens a modal with no sign in options:

![image](https://github.com/Web3Auth/web3auth-pnp-examples/assets/2058962/5738b454-9e00-4092-af7c-db48ebb9168b)

The project stack is Vite, React and Typescript. I closely followed the [react-vite-evm-modal-example](https://github.com/Web3Auth/web3auth-pnp-examples/tree/main/web-modal-sdk/evm/react-vite-evm-modal-example).

**Comment by blockiosaurus** [comment]
I am also seeing this issue on my site.
